name: Sbom CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
            java-version: '11'
            distribution: 'temurin'

      - name: Installing maven
        run: mvn -version

      - name: Installing Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.5
      - run: gradle --version

      - name: Installing Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: node --v

      - name: Installing Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo version

      - name: Test
        run: go test -v ./...


  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...